import type { LlmModel } from "./types";

// ----------------------------------------------------------------------

/**
 * Curated history of landmark large language models. Data is static (no
 * backend). Following the changelog «NEVER invented» rule: unknown numeric
 * facts are `null`, undisclosed params are `null`. Each entry carries an
 * official source URL. Facts researched and adversarially fact-checked against
 * public announcements/papers. Ordering here is not significant — the view
 * sorts by `releaseDate`.
 */
export const LLM_MODELS: LlmModel[] = [
  {
    id: "openai-gpt-1",
    slug: "gpt-1",
    vendor: "OpenAI",
    name: "GPT-1",
    releaseDate: "2018-06-11",
    contextTokens: 512,
    params: "117M",
    highlight: "Первая GPT: доказала, что предобучение на неразмеченном тексте + дообучение работает.",
    description: "GPT-1 представлена в статье «Improving Language Understanding by Generative Pre-Training» и стала первой моделью линейки generative pre-trained transformer от OpenAI. Она ввела двухэтапный подход: генеративное предобучение декодер-трансформера (12 слоёв, 117M параметров) на большом корпусе неразмеченного текста с последующим supervised-дообучением под конкретные задачи. Именно этот decoder-only рецепт лёг в основу всех последующих GPT.",
    capabilities: ["decoder-only", "pretraining", "transformer", "research"],
    sourceUrl: "https://openai.com/index/language-unsupervised/",
  },
  {
    id: "google-bert",
    slug: "bert",
    vendor: "Google",
    name: "BERT",
    releaseDate: "2018-10-11",
    contextTokens: 512,
    params: "340M",
    highlight: "Двунаправленный трансформер-энкодер, задавший стандарт предобучения в NLP.",
    description: "BERT (Bidirectional Encoder Representations from Transformers) представлен исследователями Google AI Language в статье на arXiv 11 октября 2018 года. Модель впервые применила глубокое двунаправленное предобучение через masked language modeling и next sentence prediction, что позволило дообучать её под конкретные задачи с минимальными изменениями. BERT установил новые state-of-the-art результаты на 11 NLP-бенчмарках (включая GLUE и SQuAD) и стал фундаментом для целого поколения энкодерных моделей. Версия BERT-Large содержала 340 млн параметров.",
    capabilities: ["encoder-only", "open-weights", "NLP", "fine-tuning"],
    sourceUrl: "https://arxiv.org/abs/1810.04805",
  },
  {
    id: "openai-gpt-2",
    slug: "gpt-2",
    vendor: "OpenAI",
    name: "GPT-2",
    releaseDate: "2019-02-14",
    contextTokens: 1024,
    params: "1.5B",
    highlight: "1.5B-модель, которую сначала «побоялись» выложить целиком из-за риска фейков.",
    description: "GPT-2 анонсирована 14 февраля 2019 года как языковая модель на 1.5 млрд параметров, обученная на 8 млн веб-страниц. OpenAI применила поэтапный релиз: полную модель сочли слишком опасной и выкладывали версии постепенно, полностью открыв веса лишь 5 ноября 2019 года. Модель показала связную генерацию длинного текста без дообучения под задачу и запустила публичную дискуссию о рисках генеративного ИИ.",
    capabilities: ["text-generation", "zero-shot", "staged-release", "open-weights"],
    sourceUrl: "https://openai.com/index/better-language-models/",
  },
  {
    id: "openai-gpt-3",
    slug: "gpt-3",
    vendor: "OpenAI",
    name: "GPT-3",
    releaseDate: "2020-05-28",
    contextTokens: 2048,
    params: "175B",
    highlight: "175B параметров и few-shot in-context learning без изменения весов.",
    description: "GPT-3 представлена в статье «Language Models are Few-Shot Learners» (arXiv, 28 мая 2020) — авторегрессионная модель на 175 млрд параметров, в 10 раз больше любой предыдущей неразреженной модели. Ключевой вывод: масштаб резко улучшает few-shot-обучение — модель решает задачи по нескольким примерам прямо в промпте, без градиентных обновлений. Она задала архитектурную базу для API OpenAI и последующего ChatGPT.",
    capabilities: ["few-shot", "in-context-learning", "175B", "api"],
    sourceUrl: "https://arxiv.org/abs/2005.14165",
  },
  {
    id: "google-palm",
    slug: "palm",
    vendor: "Google",
    name: "PaLM",
    releaseDate: "2022-04-04",
    contextTokens: 2048,
    params: "540B",
    highlight: "Плотная модель на 540 млрд параметров, обученная на системе Pathways.",
    description: "PaLM (Pathways Language Model) анонсирована Google Research 4 апреля 2022 года в блоге компании (статья на arXiv опубликована 5 апреля). Это плотный авторегрессионный трансформер на 540 млрд параметров, обученный на 780 млрд токенов с помощью новой системы Pathways на двух подах TPU v4. PaLM продемонстрировала прорывные результаты в многошаговом рассуждении с chain-of-thought промптингом и превзошла среднего человека на бенчмарке BIG-bench. Модель обучалась также в масштабах 8B и 62B параметров для изучения законов масштабирования.",
    capabilities: ["reasoning", "code", "multilingual", "few-shot", "chain-of-thought"],
    sourceUrl: "https://arxiv.org/abs/2204.02311",
  },
  {
    id: "openai-gpt-3-5",
    slug: "gpt-3-5",
    vendor: "OpenAI",
    name: "GPT-3.5 / ChatGPT",
    releaseDate: "2022-11-30",
    contextTokens: 4096,
    params: null,
    highlight: "Запуск ChatGPT — самый быстрый в истории выход продукта на миллион пользователей.",
    description: "30 ноября 2022 года OpenAI выпустила ChatGPT — диалогового ассистента, дообученного от модели серии GPT-3.5 с помощью RLHF (обучение с подкреплением на человеческой обратной связи). Диалоговый формат позволил модели вести беседу, признавать ошибки и отклонять недопустимые запросы. За пять дней сервис набрал более миллиона пользователей и запустил массовую волну интереса к генеративному ИИ.",
    capabilities: ["chat", "RLHF", "instruction-following", "assistant"],
    sourceUrl: "https://openai.com/index/chatgpt/",
  },
  {
    id: "meta-llama-1",
    slug: "llama-1",
    vendor: "Meta",
    name: "LLaMA",
    releaseDate: "2023-02-24",
    contextTokens: 2048,
    params: "7B / 13B / 33B / 65B",
    highlight: "Открытые веса, с которых начался бум локальных LLM: 13B обошла GPT-3 175B.",
    description: "Первое поколение больших языковых моделей Meta, выпущенное для исследователей 24 февраля 2023 года в размерах 7B, 13B, 33B и 65B параметров с контекстом 2048 токенов. Модели обучались только на публичных данных (до 1,4 трлн токенов), и меньшие версии соперничали с гораздо более крупными конкурентами — LLaMA-13B превзошла GPT-3 175B на большинстве бенчмарков. Хотя веса выдавались по заявкам и только для research, их утечка запустила волну открытых LLM и дообучений (Alpaca, Vicuna и другие).",
    capabilities: ["open-weights", "research-only", "text", "foundational"],
    sourceUrl: "https://ai.meta.com/blog/large-language-model-llama-meta-ai/",
  },
  {
    id: "openai-gpt-4",
    slug: "gpt-4",
    vendor: "OpenAI",
    name: "GPT-4",
    releaseDate: "2023-03-14",
    contextTokens: 8192,
    params: null,
    highlight: "Первая мультимодальная GPT: принимает изображения и проходит экзамены на уровне человека.",
    description: "GPT-4 представлена 14 марта 2023 года как большая мультимодальная модель, принимающая на вход текст и изображения и выдающая текст. Она демонстрирует человеческий уровень на профессиональных и академических тестах — например, сдаёт имитацию адвокатского экзамена в топ-10% участников. Число параметров OpenAI не раскрыла; базовая версия давала 8192 токена контекста, вариант gpt-4-32k — 32 768 токенов.",
    capabilities: ["multimodal", "vision", "reasoning", "system-prompt"],
    sourceUrl: "https://openai.com/index/gpt-4-research/",
  },
  {
    id: "anthropic-claude-1",
    slug: "claude-1",
    vendor: "Anthropic",
    name: "Claude 1",
    releaseDate: "2023-03-14",
    contextTokens: 9000,
    params: null,
    highlight: "Первая публичная модель Anthropic — ассистент, обученный по методу Constitutional AI быть полезным, честным и безвредным.",
    description: "14 марта 2023 года Anthropic представила Claude вместе с более лёгкой версией Claude Instant, открыв доступ через чат и API. Модель обучалась по фирменному подходу Constitutional AI и позиционировалась как более безопасная и управляемая альтернатива ChatGPT. Ранними партнёрами стали Notion, Quora (Poe) и DuckDuckGo. Стартовое контекстное окно составляло около 9K токенов.",
    capabilities: ["text", "chat", "coding", "summarization", "constitutional-ai"],
    sourceUrl: "https://www.anthropic.com/news/introducing-claude",
  },
  {
    id: "others-yandexgpt",
    slug: "yandexgpt",
    vendor: "Yandex",
    name: "YandexGPT",
    releaseDate: "2023-05-17",
    contextTokens: null,
    params: null,
    highlight: "Первая генеративная LLM Яндекса, встроенная в голосового ассистента Алису.",
    description: "YandexGPT (изначально анонсирован как YaLM 2.0 в феврале 2023) официально представлен 17 мая 2023 года. Модель умеет генерировать и обрабатывать текст, выполнять задачи и учитывать контекст диалога; сразу после запуска она была подключена к виртуальному ассистенту Алисе. Параметры и размер контекста официально не раскрывались. В сентябре 2023 вышла улучшенная YandexGPT 2.",
    capabilities: ["russian", "assistant", "text-generation", "closed-weights"],
    sourceUrl: "https://yandex.com/company/news/17-05-23",
  },
  {
    id: "anthropic-claude-2",
    slug: "claude-2",
    vendor: "Anthropic",
    name: "Claude 2",
    releaseDate: "2023-07-11",
    contextTokens: 100000,
    params: null,
    highlight: "Прорыв по длине контекста: 100K токенов — можно загрузить сотни страниц или целую книгу в один запрос.",
    description: "11 июля 2023 года Anthropic выпустила Claude 2 в публичную бету с контекстным окном на 100K токенов, загрузкой файлов и заметно улучшенными навыками кода и математики (HumanEval 71.2%, GSM8k 88.0%). 100K-контекст сделал модель лидером по объёму входных данных на фоне 8K/32K у GPT-4 того времени. Появился отдельный сайт claude.ai для широкого доступа.",
    capabilities: ["text", "chat", "long-context", "coding", "math", "file-upload"],
    sourceUrl: "https://www.anthropic.com/news/claude-2",
  },
  {
    id: "meta-llama-2",
    slug: "llama-2",
    vendor: "Meta",
    name: "Llama 2",
    releaseDate: "2023-07-18",
    contextTokens: 4096,
    params: "7B / 13B / 70B",
    highlight: "Первая открытая модель Meta, разрешённая для коммерческого использования.",
    description: "Второе поколение Llama, представленное 18 июля 2023 года совместно с Microsoft, стало первой моделью семейства, доступной бесплатно и для research, и для коммерческого применения. Выпущена в размерах 7B, 13B и 70B параметров с удвоенным контекстом 4096 токенов и обучена на 2 трлн токенов. Вместе с базовыми моделями вышла чат-версия Llama 2-Chat, дообученная через SFT и RLHF, что сделало Llama полноценной основой для продуктовых ассистентов с открытыми весами.",
    capabilities: ["open-weights", "commercial-license", "chat", "RLHF", "text"],
    sourceUrl: "https://about.fb.com/news/2023/07/llama-2/",
  },
  {
    id: "others-qwen",
    slug: "qwen",
    vendor: "Alibaba",
    name: "Qwen (Qwen-7B)",
    releaseDate: "2023-08-03",
    contextTokens: 8192,
    params: "7B",
    highlight: "Дебют открытой линейки Alibaba — одна из первых китайских LLM с коммерчески доступными весами.",
    description: "Qwen-7B (Tongyi Qianwen) и Qwen-7B-Chat выпущены Alibaba Cloud 3 августа 2023 года на ModelScope и Hugging Face с техническим отчётом. Базовая модель на 7B параметров, обученная на более чем 2,2 трлн токенов веб-текстов, книг и кода, превзошла аналоги своего размера и даже часть 13B-моделей на MMLU, C-Eval, GSM8K и HumanEval. Это один из первых крупных китайских LLM с открытыми весами под разрешительной лицензией, задавший тон всей будущей линейке Qwen.",
    capabilities: ["open-weights", "multilingual", "code", "chat"],
    sourceUrl: "https://github.com/QwenLM/Qwen",
  },
  {
    id: "mistral-ai-mistral-7b",
    slug: "mistral-7b",
    vendor: "Mistral AI",
    name: "Mistral 7B",
    releaseDate: "2023-09-27",
    contextTokens: 8192,
    params: "7.3B",
    highlight: "Открытая 7B-модель, обошедшая Llama 2 13B и задавшая стандарт для компактных LLM.",
    description: "Первая модель парижской Mistral AI, выпущенная под лицензией Apache 2.0. При 7.3 млрд параметров она превосходила Llama 2 13B на всех бенчмарках и приближалась к Llama 1 34B. Использовала Grouped-Query Attention (GQA) для быстрого инференса и Sliding Window Attention (SWA) для работы с длинными последовательностями. Стала эталоном эффективности среди небольших открытых моделей.",
    capabilities: ["open-weights", "apache-2.0", "text", "code", "efficient", "GQA", "SWA"],
    sourceUrl: "https://mistral.ai/news/announcing-mistral-7b/",
  },
  {
    id: "google-gemini-1-0",
    slug: "gemini-1-0",
    vendor: "Google",
    name: "Gemini 1.0",
    releaseDate: "2023-12-06",
    contextTokens: 32768,
    params: null,
    highlight: "Первая нативно мультимодальная модель Google в трёх размерах: Ultra, Pro, Nano.",
    description: "Gemini 1.0 анонсирована Сундаром Пичаи и Демисом Хассабисом 6 декабря 2023 года как самая мощная на тот момент модель Google. Она изначально спроектирована мультимодальной — понимает и комбинирует текст, код, аудио, изображения и видео — и выпущена в трёх размерах: Ultra для сложных задач, Pro для широкого спектра и Nano для устройств. Gemini Ultra стала первой моделью, превзошедшей экспертов-людей на бенчмарке MMLU с результатом 90.0%. Число параметров официально не раскрывалось.",
    capabilities: ["multimodal", "reasoning", "code", "on-device"],
    sourceUrl: "https://blog.google/technology/ai/google-gemini-ai/",
  },
  {
    id: "mistral-ai-mixtral-8x7b",
    slug: "mixtral-8x7b",
    vendor: "Mistral AI",
    name: "Mixtral 8x7B",
    releaseDate: "2023-12-11",
    contextTokens: 32768,
    params: "46.7B total / 12.9B active",
    highlight: "Первая открытая sparse MoE-модель, обошедшая Llama 2 70B при в 6 раз более быстром инференсе.",
    description: "Первая открытая модель Mistral с архитектурой sparse mixture-of-experts (SMoE) под лицензией Apache 2.0. Из 8 экспертов на каждом слое активируются только два, поэтому при 46.7 млрд суммарных параметров модель работает со скоростью и стоимостью 12.9B-модели. Обходит Llama 2 70B на большинстве бенчмарков и соответствует или превосходит GPT-3.5, поддерживает контекст 32k токенов и пять языков.",
    capabilities: ["open-weights", "apache-2.0", "mixture-of-experts", "multilingual", "code", "32k-context"],
    sourceUrl: "https://mistral.ai/news/mixtral-of-experts/",
  },
  {
    id: "others-phi-2",
    slug: "phi-2",
    vendor: "Microsoft",
    name: "Phi-2",
    releaseDate: "2023-12-12",
    contextTokens: 2048,
    params: "2.7B",
    highlight: "Маленькая модель на 2.7B, обходящая модели в 25 раз крупнее на рассуждениях.",
    description: "Phi-2 — компактная модель Microsoft Research на 2,7 млрд параметров, выпущенная 12 декабря 2023 года в каталоге Azure AI Studio. Несмотря на размер, она превосходит Mistral и Llama-2 на 7B и 13B, а на задачах кодинга и математики обгоняет даже Llama-2-70B. Успех приписывают «учебному» качеству данных (синтетика + отфильтрованный веб) и передаче знаний от Phi-1.5. Обучена на 1,4 трлн токенов за 14 дней на 96 A100; это базовая модель без RLHF и instruct-тюнинга.",
    capabilities: ["small-model", "reasoning", "code", "math", "base-model"],
    sourceUrl: "https://www.microsoft.com/en-us/research/blog/phi-2-the-surprising-power-of-small-language-models/",
  },
  {
    id: "google-gemini-1-5",
    slug: "gemini-1-5",
    vendor: "Google",
    name: "Gemini 1.5",
    releaseDate: "2024-02-15",
    contextTokens: 1000000,
    params: null,
    highlight: "Контекстное окно до 1 млн токенов на архитектуре Mixture-of-Experts.",
    description: "Gemini 1.5 представлена Google 15 февраля 2024 года как модель следующего поколения на архитектуре Mixture-of-Experts. Ключевой прорыв — контекстное окно до 1 млн токенов (в исследованиях протестировано до 10 млн), что позволяет обрабатывать час видео, 11 часов аудио или свыше 700 тысяч слов за один проход. Gemini 1.5 Pro достигла качества уровня 1.0 Ultra при меньших вычислительных затратах и показала 99% точности в тесте Needle In A Haystack. Стандартное окно составляло 128K токенов, расширенное до 1M — в приватном превью. Число параметров не раскрывалось.",
    capabilities: ["multimodal", "long-context", "MoE", "reasoning", "code"],
    sourceUrl: "https://blog.google/innovation-and-ai/products/google-gemini-next-generation-model-february-2024/",
  },
  {
    id: "mistral-ai-mistral-large",
    slug: "mistral-large",
    vendor: "Mistral AI",
    name: "Mistral Large",
    releaseDate: "2024-02-26",
    contextTokens: 32768,
    params: null,
    highlight: "Первая флагманская закрытая модель Mistral, конкурент GPT-4, с запуском ассистента Le Chat.",
    description: "Флагманская проприетарная модель Mistral AI с топовыми способностями к рассуждению, позиционировавшаяся как конкурент GPT-4 и Claude 2. Нативно владеет английским, французским, испанским, немецким и итальянским, сильна в коде и математике, поддерживает контекст 32k токенов. Одновременно с моделью Mistral запустила чат-ассистент Le Chat и объявила о партнёрстве с Microsoft для дистрибуции через Azure. Число параметров не раскрывалось.",
    capabilities: ["proprietary", "reasoning", "multilingual", "code", "math", "32k-context", "api"],
    sourceUrl: "https://mistral.ai/news/mistral-large/",
  },
  {
    id: "anthropic-claude-3-opus",
    slug: "claude-3-opus",
    vendor: "Anthropic",
    name: "Claude 3 Opus",
    releaseDate: "2024-03-04",
    contextTokens: 200000,
    params: null,
    highlight: "Флагман семейства Claude 3 — обошёл конкурентов на MMLU, GPQA и GSM8K и добавил мультимодальность.",
    description: "4 марта 2024 года Anthropic анонсировала семейство Claude 3 из трёх моделей; Opus — самая мощная, лидировавшая на ключевых бенчмарках (MMLU, GPQA, GSM8K) и показавшая почти идеальный recall в тесте Needle In A Haystack. Все модели получили окно 200K токенов и зрение — умеют читать фото, графики и технические диаграммы. Задан размерный нейминг Opus/Sonnet/Haiku, который структурирует линейку Claude до сих пор.",
    capabilities: ["multimodal", "vision", "reasoning", "long-context", "coding"],
    sourceUrl: "https://www.anthropic.com/news/claude-3-family",
  },
  {
    id: "anthropic-claude-3-sonnet",
    slug: "claude-3-sonnet",
    vendor: "Anthropic",
    name: "Claude 3 Sonnet",
    releaseDate: "2024-03-04",
    contextTokens: 200000,
    params: null,
    highlight: "Сбалансированная модель Claude 3 — вдвое быстрее Claude 2 при более высоком интеллекте.",
    description: "Средняя модель семейства Claude 3, представленная 4 марта 2024 года вместе с Opus и Haiku. Sonnet оптимизирована под баланс скорости, стоимости и качества: примерно вдвое быстрее Claude 2/2.1 при более высоком интеллекте, хорош для поиска знаний и автоматизации. Как и вся линейка, получила окно 200K токенов и мультимодальное зрение; доступна в claude.ai, API, Amazon Bedrock и Google Vertex AI.",
    capabilities: ["multimodal", "vision", "chat", "long-context", "coding"],
    sourceUrl: "https://www.anthropic.com/news/claude-3-family",
  },
  {
    id: "anthropic-claude-3-haiku",
    slug: "claude-3-haiku",
    vendor: "Anthropic",
    name: "Claude 3 Haiku",
    releaseDate: "2024-03-04",
    contextTokens: 200000,
    params: null,
    highlight: "Самая быстрая и дешёвая модель Claude 3 — читает плотную arXiv-статью за пару секунд.",
    description: "Самая компактная и быстрая модель семейства Claude 3, анонсированная 4 марта 2024 года. Haiku позиционировалась как самая экономичная модель на рынке в своём классе интеллекта: может прочитать насыщенную данными научную статью на ~10K токенов с графиками менее чем за три секунды. Разделяет с семейством окно 200K токенов и мультимодальные способности.",
    capabilities: ["multimodal", "vision", "fast", "low-cost", "long-context"],
    sourceUrl: "https://www.anthropic.com/news/claude-3-family",
  },
  {
    id: "others-command-r",
    slug: "command-r",
    vendor: "Cohere",
    name: "Command R",
    releaseDate: "2024-03-11",
    contextTokens: 128000,
    params: "35B",
    highlight: "Enterprise-модель Cohere, заточенная под RAG и использование инструментов.",
    description: "Command R представлена Cohere 11 марта 2024 года — генеративная модель на 35B параметров с контекстом 128K токенов, оптимизированная под retrieval-augmented generation (RAG), вызов внешних API и инструментов. Она нацелена на масштабные продакшн-нагрузки: высокая точность RAG с цитированием, низкая задержка, сильная поддержка 10 ключевых языков и низкая цена. Веса выложены на Hugging Face для исследований; вскоре вышла старшая версия Command R+.",
    capabilities: ["RAG", "tool-use", "long-context", "multilingual", "enterprise"],
    sourceUrl: "https://docs.cohere.com/docs/command-r",
  },
  {
    id: "others-grok-1",
    slug: "grok-1",
    vendor: "xAI",
    name: "Grok-1",
    releaseDate: "2024-03-17",
    contextTokens: 8192,
    params: "314B (MoE)",
    highlight: "Крупнейшая на момент выхода открытая модель — 314B параметров MoE под Apache 2.0.",
    description: "Grok-1 — базовая модель xAI, анонсированная в ноябре 2023 года и выпущенная как открытые веса 17 марта 2024 года под лицензией Apache 2.0. Это разреженная Mixture-of-Experts архитектура на 314 млрд параметров (около 25% весов активны на токен) — крупнейшая открытая модель на тот момент. Опубликован сырой чекпойнт после претрейна, без файнтюна под диалог; веса и код выложены на GitHub и Hugging Face.",
    capabilities: ["open-weights", "MoE", "base-model", "reasoning"],
    sourceUrl: "https://x.ai/news/grok-os",
  },
  {
    id: "meta-llama-3",
    slug: "llama-3",
    vendor: "Meta",
    name: "Llama 3",
    releaseDate: "2024-04-18",
    contextTokens: 8192,
    params: "8B / 70B",
    highlight: "Новый уровень качества открытых моделей масштаба 8B и 70B.",
    description: "Третье поколение Llama вышло 18 апреля 2024 года в размерах 8B и 70B (базовые и instruct-версии) и задало новый state-of-the-art для открытых моделей этих масштабов. Обучена на более чем 15 трлн токенов — в семь раз больше, чем Llama 2, с вчетверо большим объёмом кода, использует токенизатор со словарём 128K и grouped-query attention. Контекст расширен до 8192 токенов; эта версия легла в основу ассистента Meta AI.",
    capabilities: ["open-weights", "instruct", "GQA", "code", "text"],
    sourceUrl: "https://ai.meta.com/blog/meta-llama-3/",
  },
  {
    id: "others-phi-3",
    slug: "phi-3",
    vendor: "Microsoft",
    name: "Phi-3 (mini)",
    releaseDate: "2024-04-23",
    contextTokens: 128000,
    params: "3.8B",
    highlight: "SLM на 3.8B уровня GPT-3.5, помещающийся на телефон, с контекстом до 128K.",
    description: "Phi-3-mini — открытая малая модель Microsoft на 3,8 млрд параметров, выпущенная 23 апреля 2024 года на Azure AI Studio, Hugging Face и Ollama в вариантах контекста 4K и 128K токенов. Обученная на 3,3 трлн токенов отфильтрованных веб- и синтетических данных, она сопоставима с Mixtral 8x7B и GPT-3.5 (69% MMLU, 8.38 MT-bench), при этом достаточно компактна для запуска на телефоне. Позже семейство пополнили Phi-3-small (7B), Phi-3-medium (14B) и мультимодальная Phi-3-vision.",
    capabilities: ["small-model", "open-weights", "on-device", "long-context", "reasoning"],
    sourceUrl: "https://azure.microsoft.com/en-us/blog/introducing-phi-3-redefining-whats-possible-with-slms/",
  },
  {
    id: "deepseek-deepseek-v2",
    slug: "deepseek-v2",
    vendor: "DeepSeek",
    name: "DeepSeek-V2",
    releaseDate: "2024-05-07",
    contextTokens: 128000,
    params: "236B (21B активных, MoE)",
    highlight: "Открытая MoE-модель, представившая Multi-head Latent Attention и резко удешевившая инференс.",
    description: "DeepSeek-V2 — открытая Mixture-of-Experts модель на 236 млрд параметров, из которых на токен активируется лишь 21 млрд. Она ввела архитектуру Multi-head Latent Attention (MLA), сжимающую KV-кэш на 93,3%, и DeepSeekMoE для экономичного обучения — на 42,5% дешевле, чем DeepSeek 67B. Модель обучена на 8,1 трлн токенов и поддерживает контекст до 128K благодаря YaRN. Именно V2 задала фирменную для DeepSeek связку эффективности и низкой цены.",
    capabilities: ["open-weights", "MoE", "MLA", "long-context", "code", "reasoning"],
    sourceUrl: "https://arxiv.org/abs/2405.04434",
  },
  {
    id: "openai-gpt-4o",
    slug: "gpt-4o",
    vendor: "OpenAI",
    name: "GPT-4o",
    releaseDate: "2024-05-13",
    contextTokens: 128000,
    params: null,
    highlight: "«Omni»-модель: единая сеть для текста, аудио и изображений с почти живой скоростью речи.",
    description: "GPT-4o («o» — omni) представлена 13 мая 2024 года как единая end-to-end модель, обученная сразу на тексте, аудио и изображениях, а не как связка отдельных моделей. Она отвечает на аудио за ~320 мс (сопоставимо со временем реакции человека в разговоре), держит уровень GPT-4 Turbo по тексту и коду, но вдвое дешевле в API и заметно сильнее в мультиязычных, аудио- и визуальных задачах. Впервые лучшая модель OpenAI стала доступна и бесплатным пользователям.",
    capabilities: ["multimodal", "audio", "vision", "realtime", "faster"],
    sourceUrl: "https://openai.com/index/hello-gpt-4o/",
  },
  {
    id: "others-qwen2",
    slug: "qwen2",
    vendor: "Alibaba",
    name: "Qwen2",
    releaseDate: "2024-06-07",
    contextTokens: 128000,
    params: "0.5B–72B",
    highlight: "Второе поколение Qwen: до 72B, контекст 128K и обгон Llama 3 70B на бенчмарках.",
    description: "Серия Qwen2 выпущена Alibaba Cloud 7 июня 2024 года: пять размеров от 0.5B до 72B плюс MoE-модель Qwen2-57B-A14B, обученные на 7 трлн токенов и 27+ языках. Флагман Qwen2-72B-Instruct поддерживает контекст до 128K токенов (через YARN) и превзошёл Llama 3 70B и Mixtral 8x22B на MMLU, MMLU-Pro, HumanEval и GSM8K. Все модели используют Grouped Query Attention для ускорения инференса; часть весов открыта.",
    capabilities: ["open-weights", "multilingual", "MoE", "long-context", "code", "math"],
    sourceUrl: "https://qwenlm.github.io/blog/qwen2/",
  },
  {
    id: "anthropic-claude-3-5-sonnet",
    slug: "claude-3-5-sonnet",
    vendor: "Anthropic",
    name: "Claude 3.5 Sonnet",
    releaseDate: "2024-06-21",
    contextTokens: 200000,
    params: null,
    highlight: "Обошла Claude 3 Opus по интеллекту при цене и скорости среднего уровня — и принесла Artifacts.",
    description: "21 июня 2024 года Anthropic выпустила Claude 3.5 Sonnet — первую модель поколения 3.5, превзошедшую даже Claude 3 Opus на бенчмарках рассуждений (GPQA, MMLU) и кода (HumanEval) при вдвое большей скорости. В агентном тесте кода решила 64% задач против 38% у Opus. Одновременно представлена функция Artifacts — динамическое рабочее окно для кода и документов. Окно 200K токенов, цена $3/$15 за млн токенов.",
    capabilities: ["multimodal", "vision", "reasoning", "coding", "artifacts", "long-context"],
    sourceUrl: "https://www.anthropic.com/news/claude-3-5-sonnet",
  },
  {
    id: "meta-llama-3-1-405b",
    slug: "llama-3-1-405b",
    vendor: "Meta",
    name: "Llama 3.1 405B",
    releaseDate: "2024-07-23",
    contextTokens: 128000,
    params: "405B",
    highlight: "Первая открытая frontier-модель, соперничающая с GPT-4o и Claude 3.5 Sonnet.",
    description: "Выпущенная 23 июля 2024 года Llama 3.1 405B стала крупнейшей и первой по-настоящему frontier-моделью Meta с открытыми весами, сравнимой с закрытыми GPT-4o и Claude 3.5 Sonnet по знаниям, математике, использованию инструментов и мультиязычности. Все модели релиза (8B, 70B и 405B) получили контекст 128K токенов и поддержку восьми языков. Обучение на 15+ трлн токенов шло на более чем 16 тыс. GPU H100; открытые веса позволили сообществу генерировать синтетические данные и дистиллировать модель.",
    capabilities: ["open-weights", "frontier", "long-context", "multilingual", "tool-use", "instruct"],
    sourceUrl: "https://ai.meta.com/blog/meta-llama-3-1/",
  },
  {
    id: "others-grok-2",
    slug: "grok-2",
    vendor: "xAI",
    name: "Grok-2",
    releaseDate: "2024-08-14",
    contextTokens: 128000,
    params: null,
    highlight: "Фронтир-модель xAI с чатом, кодом, рассуждениями и генерацией изображений.",
    description: "Grok-2 и облегчённый Grok-2 mini выпущены в бете 14 августа 2024 года как значительный шаг вперёд относительно Grok-1.5. Модель достигла конкурентного с фронтир-моделями уровня в GPQA, MMLU, MMLU-Pro и MATH, а также показала сильные результаты в vision-задачах (MathVista, DocVQA). Ранняя версия под именем «sus-column-r» тестировалась на LMSYS-лидерборде, обходя Claude 3.5 Sonnet и GPT-4-Turbo. Добавлена генерация изображений через Flux от Black Forest Labs.",
    capabilities: ["reasoning", "code", "multimodal", "vision", "image-generation"],
    sourceUrl: "https://x.ai/news/grok-2",
  },
  {
    id: "openai-o1",
    slug: "o1",
    vendor: "OpenAI",
    name: "o1",
    releaseDate: "2024-09-12",
    contextTokens: 200000,
    params: null,
    highlight: "Первая reasoning-модель: «думает» перед ответом, масштабируя вычисления на инференсе.",
    description: "o1 — первая reasoning-модель OpenAI, обученная тратить больше времени на размышление перед ответом за счёт скрытой цепочки рассуждений. Preview-версия вышла 12 сентября 2024 года, полная o1 — 5 декабря 2024 года в рамках «12 Days of OpenAI». Она резко превзошла GPT-4o в математике, науке и программировании (например, 83% на отборочном тесте IMO против 13% у GPT-4o) и ввела третью ось масштабирования — вычисления во время инференса.",
    capabilities: ["reasoning", "chain-of-thought", "inference-scaling", "STEM"],
    sourceUrl: "https://openai.com/index/introducing-openai-o1-preview/",
  },
  {
    id: "google-gemini-2-0",
    slug: "gemini-2-0",
    vendor: "Google",
    name: "Gemini 2.0",
    releaseDate: "2024-12-11",
    contextTokens: 1000000,
    params: null,
    highlight: "Модель «агентной эры» с нативной генерацией изображений и аудио.",
    description: "Gemini 2.0 анонсирована Google 11 декабря 2024 года как модель, построенная для «агентной эры». Первой вышла экспериментальная версия Gemini 2.0 Flash, которая превзошла 1.5 Pro на ключевых бенчмарках при вдвое большей скорости. Помимо мультимодального ввода (изображения, видео, аудио), модель получила нативный мультимодальный вывод — генерацию изображений вперемешку с текстом и управляемый многоязычный TTS. Вместе с моделью Google показала агентные прототипы Project Astra, Project Mariner и Jules. Число параметров не раскрывалось.",
    capabilities: ["multimodal", "agentic", "image-generation", "long-context", "TTS"],
    sourceUrl: "https://blog.google/technology/google-deepmind/google-gemini-ai-update-december-2024/",
  },
  {
    id: "openai-o3",
    slug: "o3",
    vendor: "OpenAI",
    name: "o3",
    releaseDate: "2024-12-20",
    contextTokens: 200000,
    params: null,
    highlight: "Прорыв в рассуждениях: рекорд на ARC-AGI и регулируемый бюджет «размышления».",
    description: "o3 анонсирована 20 декабря 2024 года в финале «12 Days of OpenAI» как преемник o1 (название o2 пропустили из-за конфликта с торговой маркой телеком-оператора O2). Модель добавила регулируемое время рассуждения (low/medium/high) и поставила рекорды на жёстких бенчмарках: 96.7% на AIME 2024, 87.7% на GPQA Diamond, 25.2% на Frontier Math и прорывные 87.5% на ARC-AGI (high-compute). На анонсе модель ушла внешним исследователям на проверку безопасности; публичный релиз o3-mini состоялся 31 января 2025 года, а полной o3 — 16 апреля 2025 года.",
    capabilities: ["reasoning", "adjustable-compute", "ARC-AGI", "frontier"],
    sourceUrl: "https://openai.com/index/introducing-o3-and-o4-mini/",
  },
  {
    id: "deepseek-deepseek-v3",
    slug: "deepseek-v3",
    vendor: "DeepSeek",
    name: "DeepSeek-V3",
    releaseDate: "2024-12-26",
    contextTokens: 128000,
    params: "671B (37B активных, MoE)",
    highlight: "Открытая MoE на 671B, обученная всего за ~5,6 млн долларов и вставшая на уровень GPT-4o.",
    description: "DeepSeek-V3 — открытая Mixture-of-Experts модель на 671 млрд параметров (37 млрд активных на токен), обученная на 14,8 трлн токенов. При обучении на 2048 GPU H800 её стоимость оценивают примерно в 5,6 млн долларов — на порядок дешевле сопоставимых западных моделей. По бенчмаркам V3 достигла паритета с GPT-4o и Claude 3.5 Sonnet, обгоняя Llama 3.1 и Qwen 2.5, и стала базой для последующей R1.",
    capabilities: ["open-weights", "MoE", "MLA", "MTP", "long-context", "code", "multilingual"],
    sourceUrl: "https://api-docs.deepseek.com/news/news1226",
  },
  {
    id: "deepseek-deepseek-r1",
    slug: "deepseek-r1",
    vendor: "DeepSeek",
    name: "DeepSeek-R1",
    releaseDate: "2025-01-20",
    contextTokens: 128000,
    params: "671B (37B активных, MoE)",
    highlight: "Открытая reasoning-модель уровня OpenAI o1, обученная в основном через RL — вызвала шок на рынке.",
    description: "DeepSeek-R1 — открытая reasoning-модель на архитектуре DeepSeek-V3 (671 млрд параметров, 37 млрд активных), развивающая способности к рассуждению через обучение с подкреплением. Ключевая идея — крупномасштабный RL по алгоритму GRPO поверх «холодного старта» на chain-of-thought данных, дающий самопроверку и коррекцию ошибок. По задачам рассуждения R1 сопоставима с OpenAI o1, но обучена гораздо дешевле; открытая публикация метода и весов вызвала резонанс на всём рынке ИИ.",
    capabilities: ["open-weights", "reasoning", "MoE", "reinforcement-learning", "chain-of-thought", "long-context"],
    sourceUrl: "https://api-docs.deepseek.com/news/news250120",
  },
  {
    id: "anthropic-claude-3-7-sonnet",
    slug: "claude-3-7-sonnet",
    vendor: "Anthropic",
    name: "Claude 3.7 Sonnet",
    releaseDate: "2025-02-24",
    contextTokens: 200000,
    params: null,
    highlight: "Первая на рынке гибридная reasoning-модель: одна модель — два режима мышления, плюс дебют Claude Code.",
    description: "24 февраля 2025 года Anthropic представила Claude 3.7 Sonnet — первую гибридную reasoning-модель, которая даёт как мгновенные ответы, так и видимое пошаговое «расширенное мышление» в одной модели. Через API можно задавать бюджет размышлений вплоть до 128K токенов вывода, торгуя скорость на качество. Модель стала state-of-the-art по коду (70.3% на SWE-bench Verified). Одновременно вышел агентный инструмент командной строки Claude Code.",
    capabilities: ["hybrid-reasoning", "extended-thinking", "multimodal", "coding", "agentic", "long-context"],
    sourceUrl: "https://www.anthropic.com/news/claude-3-7-sonnet",
  },
];
