import type { HomeSkill } from "./types";

export const SKILLS: HomeSkill[] = [
  {
    name: "Frontend Разработка",
    description: "Создание современных и адаптивных веб-интерфейсов",
    icon: "mdi:react",
    items: [
      "React",
      "TypeScript",
      "Next.js",
      "Angular",
      "Material UI",
      "Redux",
      "Tailwind CSS",
    ],
    iconSkill: [
      "logos:react",
      "logos:typescript-icon",
      "logos:nextjs-icon",
      "logos:angular-icon",
      "logos:material-ui",
      "logos:redux",
      "logos:tailwindcss-icon",
    ],
  },
  {
    name: "Backend Разработка",
    description: "Серверная разработка и реализация API",
    icon: "mdi:database",
    items: [
      "Node.js",
      "REST API",
      "Symfony",
      "Docker",
      "Express",
      "MongoDB",
      "PostgreSQL",
      "Mariadb",
    ],
    iconSkill: [
      "logos:nodejs-icon",
      "logos:rest",
      "logos:symfony",
      "logos:docker",
      "logos:express",
      "logos:mongodb-icon",
      "logos:postgresql",
      "logos:mariadb",
    ],
  },
  {
    name: "Инструменты и DevOps",
    description: "Инструменты разработки и развертывания",
    icon: "mdi:tools",
    items: [
      "Git",
      "Webpack",
      "Figma",
      "Docker",
      "AWS",
      "CI/CD",
      "Jest",
      "Cypress",
    ],
    iconSkill: [
      "logos:git-icon",
      "logos:webpack",
      "logos:figma",
      "logos:docker",
      "logos:aws",
      "logos:jenkins",
      "logos:jest",
      "logos:cypress",
    ],
  },
];
